version: '3'
services:
  web:
    image: book:test
    ports:
      - "8080:80"
    # volumes:
    #   - .:/var/www/html
    depends_on:
      - db
    environment:
      BOOKSHELF_DEBUG: "true"
      BOOKSHELF_BACKEND: mysql
      CLOUDSQL_CONNECTION_NAME: host=db
      CLOUDSQL_DATABASE_NAME: bsdb
      CLOUDSQL_USER: bsuser
      CLOUDSQL_PASSWORD: bspass
      CLOUDSQL_PORT: 3306
      GELF_HOST: 10.4.8.93
      GELF_PORT: 12203
  db:
    image: mariadb:10.4.7-bionic
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bsdb
      MYSQL_USER: bsuser
      MYSQL_PASSWORD: bspass
