apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
      - image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
        name: {{ .Release.Name }}-web
        env:
        - name: BOOKSHELF_DEBUG
          value: "{{ .Values.web.debug }}"
        - name: BOOKSHELF_BACKEND
          value: "mysql"
        - name: CLOUDSQL_CONNECTION_NAME
          value: "host={{ .Release.Name }}-db"
        - name: CLOUDSQL_DATABASE_NAME
          value: "{{ .Values.credential.mysqlDatabase }}"
        - name: CLOUDSQL_USER
          value: "{{ .Values.credential.mysqlUser }}"
        - name: CLOUDSQL_PASSWORD
          value: "{{ .Values.credential.mysqlPassword }}"
        - name: CLOUDSQL_PORT
          value: "{{ .Values.credential.mysqlPort }}"
        - name: COMMIT_ID
          value: "{{ .Values.web.commitId }}"
